# Generated by Django 4.1.7 on 2023-08-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
